(function () {
  "use strict";

  const storageKey = "site-theme";
  const root = document.documentElement;
  const media = window.matchMedia("(prefers-color-scheme: dark)");
  const institutionalName =
    "Dr. Vishwanath Karad MIT World Peace University";

  function installInstitutionalLockup() {
    const bar = document.querySelector(".institution-bar");
    if (!bar || bar.querySelector(".institutional-lockup")) return;
    const inner = bar.querySelector(".institution-inner");
    if (!inner) return;

    const institutionHome = inner.querySelector(
      ".institution-home, .institution-name",
    );
    const href = institutionHome?.getAttribute("href") || "/";

    const lockup = document.createElement("a");
    lockup.className = "institutional-lockup";
    lockup.href = href;
    lockup.setAttribute("aria-label", `${institutionalName} home`);
    lockup.innerHTML =
      '<img class="institutional-lockup__logo" src="/demo-assets/brand/mitwpu-official-logo.webp" alt="" width="431" height="124" data-media-role="logo">';

    if (institutionHome) institutionHome.replaceWith(lockup);
    else inner.prepend(lockup);
  }

  function installInstitutionalNavigation() {
    const bar = document.querySelector(".institution-bar");
    if (!bar) return;
    // The release builder already ships the canonical masthead (with its
    // dropdown mega-menu). Never rebuild it flat — that would wipe the menus.
    if (bar.hasAttribute("data-global-masthead")) return;
    const inner = bar.querySelector(".institution-inner");
    if (!inner) return;

    // Older page templates only supplied the university lock-up. Create the
    // standard navigation container so every page gets the same sticky bar.
    let nav = bar.querySelector(".institution-links");
    if (!nav) {
      nav = document.createElement("nav");
      nav.className = "institution-links";
      inner.append(nav);
    }
    const themeToggle = document.querySelector("[data-theme-toggle]");
    const duplicateInstitutionalNav = document.querySelector(
      ".site-header .site-nav.institutional-nav",
    );

    /* uwp:nav — generated by tools/apply_institutional_navigation.mjs */
    const links = [
      ["About Us", "/about/"],
      ["Academics", "/academics/"],
      ["Admissions", "/admissions/"],
      ["Research", "/research/"],
      ["Administration", "/administration/"],
      ["Campus", "/life-at-mit-wpu/"],
      ["Students", "/students/"],
    ];
    /* /uwp:nav */
    const path = window.location.pathname.replace(/\/+$/, "/");
    const researchContext = /^\/(?:groups|facilities|photonics|quantum|astrophysics|bioinformatics)\//.test(path);
    nav.replaceChildren();
    nav.setAttribute("aria-label", "University navigation");
    links.forEach(([label, href]) => {
      const link = document.createElement("a");
      link.textContent = label;
      link.href = href;
      if (
        path === href
        || (href !== "/" && path.startsWith(href))
        || (href === "/research/" && researchContext)
      ) {
        link.setAttribute("aria-current", "page");
      }
      nav.append(link);
    });
    if (themeToggle) nav.append(themeToggle);
    if (duplicateInstitutionalNav && duplicateInstitutionalNav !== nav) {
      duplicateInstitutionalNav.remove();
      document.querySelector(".site-header")?.classList.add(
        "site-header--context-only",
      );
    }
  }

  function storedTheme() {
    try {
      const value = window.localStorage.getItem(storageKey);
      return value === "light" || value === "dark" ? value : "";
    } catch (_error) {
      return "";
    }
  }

  function preferredTheme() {
    return storedTheme() || (media.matches ? "dark" : "light");
  }

  function applyTheme(theme) {
    if (theme === "dark") root.setAttribute("data-theme", "dark");
    else root.setAttribute("data-theme", "light");
    document.querySelectorAll("[data-theme-toggle]").forEach((button) => {
      const dark = theme === "dark";
      button.setAttribute("aria-pressed", String(dark));
      button.setAttribute("aria-label", dark ? "Switch to light mode" : "Switch to dark mode");
      button.title = dark ? "Switch to light mode" : "Switch to dark mode";
    });
  }

  function toggleTheme() {
    const next = root.getAttribute("data-theme") === "dark" ? "light" : "dark";
    try {
      window.localStorage.setItem(storageKey, next);
    } catch (_error) {
      // The theme still changes for the current page when storage is unavailable.
    }
    applyTheme(next);
  }

  function currentMicrositeContent() {
    const path = window.location.pathname;
    if (/(?:^|\/)photonics\//.test(path)) {
      return window.PHOTONICS_SITE?.site || {};
    }
    if (/(?:^|\/)quantum\//.test(path)) {
      return window.QUANTUM_GROUP?.site || {};
    }
    if (/(?:^|\/)astrophysics\//.test(path)) {
      return window.ASTROPHYSICS_GROUP?.site || {};
    }
    if (/(?:^|\/)bioinformatics\//.test(path)) {
      return window.BIOINFORMATICS_GROUP?.site || {};
    }
    return {};
  }

  function currentPageName() {
    const name = window.location.pathname.split("/").filter(Boolean).pop() || "";
    return name.endsWith(".html") ? name : "index.html";
  }

  function applyMicrositeContent() {
    const page = currentMicrositeContent().pages?.[currentPageName()];
    if (!page) return;
    if (page.seo?.title) document.title = page.seo.title;
    if (page.seo?.description) {
      let description = document.querySelector('meta[name="description"]');
      if (!description) {
        description = document.createElement("meta");
        description.name = "description";
        document.head.append(description);
      }
      description.content = page.seo.description;
    }
    (page.text || []).forEach((item) => {
      try {
        const target = document.querySelector(item.selector);
        const node = target?.childNodes[item.node];
        if (node?.nodeType === Node.TEXT_NODE && node.nodeValue !== item.value) {
          node.nodeValue = item.value;
        }
      } catch (_error) {
        // A retired template selector must not stop the rest of the page.
      }
    });
    (page.images || []).forEach((item) => {
      try {
        const image = document.querySelector(item.selector);
        if (!(image instanceof HTMLImageElement)) return;
        if (image.getAttribute("src") !== item.src) image.setAttribute("src", item.src);
        if (image.getAttribute("alt") !== item.alt) image.setAttribute("alt", item.alt);
      } catch (_error) {
        // Ignore selectors retired by a later shared-template update.
      }
    });
  }

  function watchMicrositeContent() {
    if (!currentMicrositeContent().pages?.[currentPageName()]) return;
    applyMicrositeContent();
    if (new URLSearchParams(window.location.search).has("cms-edit")) {
      window.addEventListener("load", applyMicrositeContent, { once: true });
      return;
    }
    let queued = false;
    const observer = new MutationObserver(() => {
      if (queued) return;
      queued = true;
      window.requestAnimationFrame(() => {
        queued = false;
        applyMicrositeContent();
      });
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });
  }

  const initMobileNav = () => {
    const toggle = document.querySelector("[data-nav-toggle]");
    const nav = document.querySelector("[data-global-nav]");
    if (!toggle || !nav) return;
    const desktopNav = window.matchMedia("(min-width: 768px)");
    const setOpen = (open) => {
      nav.classList.toggle("is-open", open);
      toggle.setAttribute("aria-expanded", String(open));
      toggle.setAttribute("aria-label", open ? "Close menu" : "Open menu");
    };
    const setSubmenuOpen = (button, open) => {
      const item = button.closest(".nav-item--menu");
      if (!item) return;
      item.classList.toggle("is-open", open);
      button.setAttribute("aria-expanded", String(open));
    };
    const closeSubmenus = (except) => {
      nav.querySelectorAll(".nav-item__disclosure").forEach((button) => {
        if (button !== except) setSubmenuOpen(button, false);
      });
    };
    toggle.addEventListener("click", () => {
      setOpen(!nav.classList.contains("is-open"));
    });
    nav.addEventListener("click", (event) => {
      if (event.target.closest("a")) {
        setOpen(false);
        if (!desktopNav.matches) closeSubmenus();
      }
    });
    document.addEventListener("keydown", (event) => {
      if (event.key === "Escape") {
        setOpen(false);
        closeSubmenus();
      }
    });
    document.addEventListener("click", (event) => {
      if (
        nav.classList.contains("is-open")
        && !event.target.closest("[data-global-masthead]")
      ) {
        setOpen(false);
      }
      if (!event.target.closest("[data-global-masthead]")) closeSubmenus();
    });
    desktopNav.addEventListener("change", (event) => {
      if (event.matches) setOpen(false);
    });

    nav.querySelectorAll(".nav-item__disclosure").forEach((btn) => {
      btn.addEventListener("click", (event) => {
        event.preventDefault();
        const item = btn.closest(".nav-item--menu");
        if (!item) return;
        const open = !item.classList.contains("is-open");
        closeSubmenus(btn);
        setSubmenuOpen(btn, open);
      });
    });
  };

  const initProgrammeDirectories = () => {
    document.querySelectorAll("[data-programme-directory]").forEach((directory) => {
      const search = directory.querySelector("[data-programme-search]");
      const levelRoute = directory.querySelector("[data-programme-level-route]");
      const discipline = directory.querySelector("[data-programme-discipline]");
      const cards = Array.from(directory.querySelectorAll("[data-programme-card]"));
      const count = directory.querySelector("[data-programme-count]");
      const empty = directory.querySelector("[data-programme-empty]");
      const selectedCount = directory.querySelector("[data-programme-selected-count]");
      const compare = directory.querySelector("[data-programme-compare]");
      const clear = directory.querySelector("[data-programme-clear]");
      const comparison = directory.querySelector("[data-programme-comparison]");
      const comparisonGrid = directory.querySelector("[data-programme-comparison-grid]");
      if (!search || !discipline || cards.length === 0) return;

      const update = () => {
        const query = search.value.trim().toLocaleLowerCase();
        const selectedDiscipline = discipline.value;
        let visible = 0;
        cards.forEach((card) => {
          const matchesQuery = !query || card.dataset.search.includes(query);
          const matchesDiscipline =
            !selectedDiscipline || card.dataset.discipline === selectedDiscipline;
          const show = matchesQuery && matchesDiscipline;
          card.hidden = !show;
          if (show) visible += 1;
        });
        if (count) count.textContent = `${visible} ${visible === 1 ? "programme" : "programmes"}`;
        if (empty) empty.hidden = visible !== 0;
      };

      const selectedCards = () =>
        cards.filter((card) => card.querySelector("[data-programme-select]")?.checked);

      const updateSelection = () => {
        const selected = selectedCards().length;
        if (selectedCount) selectedCount.textContent = `${selected} selected`;
        if (compare) compare.disabled = selected === 0;
        if (clear) clear.disabled = selected === 0;
        if (selected === 0 && comparison) comparison.hidden = true;
      };

      const renderComparison = () => {
        if (!comparison || !comparisonGrid) return;
        comparisonGrid.replaceChildren();
        selectedCards().forEach((card) => {
          const article = document.createElement("article");
          const title = document.createElement("h3");
          const facts = document.createElement("p");
          const summary = document.createElement("p");
          const link = document.createElement("a");
          title.textContent = card.dataset.title;
          facts.textContent = [card.dataset.level, card.dataset.discipline, card.dataset.duration]
            .filter(Boolean)
            .join(" · ");
          summary.textContent = card.dataset.summary;
          link.href = card.dataset.href;
          link.textContent = "Programme details";
          article.append(title, facts, summary, link);
          comparisonGrid.append(article);
        });
        comparison.hidden = false;
        comparison.querySelector("h2")?.focus();
      };

      levelRoute?.addEventListener("change", () => {
        window.location.assign(levelRoute.value);
      });
      search.addEventListener("input", update);
      discipline.addEventListener("change", update);
      cards.forEach((card) => {
        card.querySelector("[data-programme-select]")?.addEventListener(
          "change",
          updateSelection,
        );
      });
      compare?.addEventListener("click", renderComparison);
      clear?.addEventListener("click", () => {
        cards.forEach((card) => {
          const checkbox = card.querySelector("[data-programme-select]");
          if (checkbox) checkbox.checked = false;
        });
        if (comparison) comparison.hidden = true;
        updateSelection();
      });
    });
  };

  installInstitutionalLockup();
  installInstitutionalNavigation();

  document.addEventListener("DOMContentLoaded", () => {
    applyTheme(preferredTheme());
    document.querySelectorAll("[data-theme-toggle]").forEach((button) => {
      button.addEventListener("click", toggleTheme);
    });
    initMobileNav();
    initProgrammeDirectories();
    watchMicrositeContent();
  });

  const followDeviceTheme = (event) => {
    if (!storedTheme()) applyTheme(event.matches ? "dark" : "light");
  };
  if (typeof media.addEventListener === "function") {
    media.addEventListener("change", followDeviceTheme);
  } else if (typeof media.addListener === "function") {
    media.addListener(followDeviceTheme);
  }
})();

/* ------------------------------------------------------------------ *
 * Global masthead dropdowns — 2-level cascading hover-intent
 * (extended for fly-outs 2026-07-25).
 * Level 1: entering a top item opens its single-column dropdown; it
 * closes ~240ms after the pointer leaves BOTH the trigger and its
 * panel, so a diagonal move into the wider panel never slams it shut.
 * Level 2: a `.nav-subitem--menu` row opens a `.nav-flyout` beside it —
 * to the right, or to the LEFT when it would clip the viewport edge.
 * The fly-out is a DOM descendant of its row, so moving into it keeps
 * the pointer inside the row; a close-delay covers the brief transit,
 * and taking over a sibling fly-out is intent-delayed so a diagonal
 * sweep toward the open panel is never hijacked by rows passed along
 * the way. `.is-open` stays the single source of truth (no raw `:hover`
 * opener that would diagonal-close), matching the CSS reveal rules.
 * Desktop pointers only; touch/mobile use the click accordion — the ▸
 * disclosure toggles the nested fly-out in place. Idempotent, so it is
 * safe to load once per page.
 * ------------------------------------------------------------------ */
(function () {
  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }
  ready(function () {
    if (document.documentElement.hasAttribute("data-nav-hover-intent")) return;
    document.documentElement.setAttribute("data-nav-hover-intent", "1");

    var desktop = window.matchMedia("(min-width: 768px)");
    var items = Array.prototype.slice.call(
      document.querySelectorAll("[data-global-masthead] .nav-item--menu")
    );
    if (!items.length) return;

    var CLOSE_DELAY = 240;           // level-1 close delay
    var FLYOUT_CLOSE_DELAY = 300;    // level-2 close delay — covers diagonal transit
    var FLYOUT_SWITCH_DELAY = 140;   // delay before a sibling fly-out takes over
    var timers = new WeakMap();      // level-1 close timers
    var closeTimers = new WeakMap(); // level-2 close timers
    var openTimers = new WeakMap();  // level-2 switch-intent timers

    function subitemsOf(item) {
      return Array.prototype.slice.call(
        item.querySelectorAll(".nav-subitem--menu")
      );
    }

    function setSubOpen(sub, open) {
      sub.classList.toggle("is-open", open);
      var disc = sub.querySelector(":scope > .nav-subitem__disclosure");
      if (disc) disc.setAttribute("aria-expanded", String(open));
    }

    function closeSub(sub) {
      clearTimeout(openTimers.get(sub));
      clearTimeout(closeTimers.get(sub));
      setSubOpen(sub, false);
    }

    function closeSiblingSubs(item, except) {
      subitemsOf(item).forEach(function (s) { if (s !== except) closeSub(s); });
    }

    // Right by default; flip to the LEFT (and point the chevron left) when the
    // panel would otherwise clip past the viewport's right edge.
    function placeFlyout(sub) {
      var fly = sub.querySelector(":scope > .nav-flyout");
      if (!fly) return;
      fly.classList.remove("nav-flyout--left");
      sub.classList.remove("is-flipped");
      if (!desktop.matches) return;                // mobile fly-outs are static
      var rect = fly.getBoundingClientRect();
      if (rect.right > document.documentElement.clientWidth - 6) {
        fly.classList.add("nav-flyout--left");
        sub.classList.add("is-flipped");
      }
    }

    function openSub(sub) {
      var item = sub.closest(".nav-item--menu");
      clearTimeout(openTimers.get(sub));
      clearTimeout(closeTimers.get(sub));
      if (item) closeSiblingSubs(item, sub);          // one fly-out per menu
      setSubOpen(sub, true);
      placeFlyout(sub);
    }

    function scheduleCloseSub(sub) {
      clearTimeout(closeTimers.get(sub));
      closeTimers.set(
        sub,
        setTimeout(function () { setSubOpen(sub, false); }, FLYOUT_CLOSE_DELAY)
      );
    }

    function closeAll(except) {
      items.forEach(function (it) {
        if (it !== except) {
          clearTimeout(timers.get(it));
          it.classList.remove("is-open");
          subitemsOf(it).forEach(closeSub);           // reset nested fly-outs too
        }
      });
    }

    function openItem(item) {
      if (!desktop.matches) return;
      clearTimeout(timers.get(item));
      closeAll(item);                                 // one menu open at a time
      item.classList.add("is-open");
    }

    items.forEach(function (item) {
      function open() { openItem(item); }
      function scheduleClose() {
        if (!desktop.matches) return;
        clearTimeout(timers.get(item));
        timers.set(item, setTimeout(function () {
          item.classList.remove("is-open");
          subitemsOf(item).forEach(closeSub);
        }, CLOSE_DELAY));
      }
      // Pointer: mouseleave does not fire while the pointer is over the panel
      // (a DOM descendant), so the menu stays open over it; the delay covers
      // the brief off-element transit in between.
      item.addEventListener("mouseenter", open);
      item.addEventListener("mouseleave", scheduleClose);
      // Keyboard parity: focus opens, focus leaving the item closes.
      item.addEventListener("focusin", open);
      item.addEventListener("focusout", function (event) {
        if (
          desktop.matches
          && !item.contains(event.relatedTarget)
          && !item.matches(":hover")
        ) {
          item.classList.remove("is-open");
          subitemsOf(item).forEach(closeSub);
        }
      });

      // ---- level-2 cascading fly-outs within this menu ----
      subitemsOf(item).forEach(function (sub) {
        sub.addEventListener("mouseenter", function () {
          if (!desktop.matches) return;
          clearTimeout(closeTimers.get(sub));         // cancel our own close
          if (sub.classList.contains("is-open")) return;
          var siblingOpen = subitemsOf(item).some(function (s) {
            return s !== sub && s.classList.contains("is-open");
          });
          if (siblingOpen) {
            // A fly-out is already open: delay the switch so a diagonal sweep
            // toward it is not hijacked by rows crossed along the way.
            clearTimeout(openTimers.get(sub));
            openTimers.set(
              sub,
              setTimeout(function () { openSub(sub); }, FLYOUT_SWITCH_DELAY)
            );
          } else {
            openSub(sub);                             // first open is instant
          }
        });
        sub.addEventListener("mouseleave", function () {
          if (!desktop.matches) return;
          clearTimeout(openTimers.get(sub));          // drop a pending switch
          scheduleCloseSub(sub);
        });
        sub.addEventListener("focusin", function () {
          if (!desktop.matches) return;
          clearTimeout(closeTimers.get(sub));
          openSub(sub);
        });
        sub.addEventListener("focusout", function (event) {
          if (
            desktop.matches
            && !sub.contains(event.relatedTarget)
            && !sub.matches(":hover")
          ) {
            closeSub(sub);
          }
        });
        // Mobile: the ▸ disclosure toggles the nested fly-out in place without
        // following the row link. Desktop keeps hover as the single opener.
        var disc = sub.querySelector(":scope > .nav-subitem__disclosure");
        if (disc) {
          disc.addEventListener("click", function (event) {
            if (desktop.matches) return;
            event.preventDefault();
            event.stopPropagation();
            var willOpen = !sub.classList.contains("is-open");
            closeSiblingSubs(item, sub);
            setSubOpen(sub, willOpen);
          });
        }
      });
    });

    // History restoration can resume a document without firing mouseenter.
    // Reconcile `.is-open` with the pointer after each initial load / BFCache
    // return so a restored menu is neither stale nor inert.
    window.addEventListener("pageshow", function () {
      window.requestAnimationFrame(function () {
        if (!desktop.matches) return;
        var hovered = items.find(function (item) {
          return item.matches(":hover");
        });
        if (hovered) openItem(hovered);
        else closeAll(null);
      });
    });

    // Click outside the masthead, or Escape, dismisses any open menu.
    document.addEventListener("click", function (event) {
      if (!event.target.closest("[data-global-masthead]")) closeAll(null);
    });
    document.addEventListener("keydown", function (event) {
      if (event.key === "Escape") closeAll(null);
    });
    // Crossing below the desktop breakpoint clears desktop open-state so the
    // mobile panel never inherits a stuck-open submenu.
    desktop.addEventListener("change", function (event) {
      if (!event.matches) closeAll(null);
    });
  });
})();
