(function () {
  "use strict";

  var storageKey = "site-theme";
  var root = document.documentElement;
  var media = window.matchMedia("(prefers-color-scheme: dark)");
  var institutionalName =
    "Dr. Vishwanath Karad MIT World Peace University";

  function installInstitutionalLockup() {
    var header = document.querySelector(".site-header");
    if (!header || header.querySelector(".institutional-lockup")) return;

    var inner = header.querySelector(".header-inner, .site-header__inner");
    if (!inner) return;

    var existingBrand = inner.querySelector(
      ":scope > .brand, :scope > .wordmark, :scope > .academic-brand"
    );
    var normalizedBrand = existingBrand
      ? existingBrand.textContent.replace(/\s+/g, " ").trim()
      : "";
    var genericBrand = normalizedBrand === "MIT World Peace University";
    var institutionHome = document.querySelector(".institution-home");
    var href = institutionHome
      ? institutionHome.getAttribute("href")
      : genericBrand && existingBrand
        ? existingBrand.getAttribute("href")
        : "/";

    var lockup = document.createElement("a");
    lockup.className = "institutional-lockup";
    lockup.href = href;
    lockup.setAttribute("aria-label", institutionalName + " home");
    lockup.innerHTML =
      '<img class="institutional-lockup__logo" src="/demo-assets/brand/mitwpu-official-logo.webp" alt="" width="431" height="124" data-media-role="logo">';

    if (genericBrand) {
      existingBrand.replaceWith(lockup);
      return;
    }

    var brands = document.createElement("div");
    brands.className = "masthead-brands";
    inner.insertBefore(brands, existingBrand || inner.firstChild);
    brands.appendChild(lockup);
    if (existingBrand) brands.appendChild(existingBrand);
  }

  function installInstitutionalNavigation() {
    var header = document.querySelector(".site-header");
    if (!header || header.querySelector(".masthead-brands")) return;

    var nav = header.querySelector(".site-nav, .primary-nav");
    if (!nav) return;

    /* uwp:nav — generated by tools/apply_institutional_navigation.mjs */
    var links = [
      ["About Us", "/about/"],
      ["Academics", "/academics/"],
      ["Research", "/research/"],
      ["Admissions", "/admissions/"],
      ["Administration", "/administration/"],
      ["Campus", "/life-at-mit-wpu/"],
      ["Students", "/students/"],
    ];
    /* /uwp:nav */
    var path = window.location.pathname.replace(/\/+$/, "/");
    nav.replaceChildren();
    links.forEach(function (item) {
      var link = document.createElement("a");
      link.textContent = item[0];
      link.href = item[1];
      if (
        path === item[1]
        || (item[1] !== "/" && path.indexOf(item[1]) === 0)
      ) {
        link.setAttribute("aria-current", "page");
      }
      nav.appendChild(link);
    });
  }

  function initMobileNav() {
    var toggle = document.querySelector("[data-nav-toggle]");
    var nav = document.querySelector("[data-global-nav]");
    if (!toggle || !nav) return;
    var desktopNav = window.matchMedia("(min-width: 768px)");

    function setOpen(open) {
      nav.classList.toggle("is-open", open);
      toggle.setAttribute("aria-expanded", String(open));
      toggle.setAttribute("aria-label", open ? "Close menu" : "Open menu");
    }

    function setSubmenuOpen(button, open) {
      var item = button.closest(".nav-item--menu");
      if (!item) return;
      item.classList.toggle("is-open", open);
      button.setAttribute("aria-expanded", String(open));
    }

    function closeSubmenus(except) {
      nav.querySelectorAll(".nav-item__disclosure").forEach(function (button) {
        if (button !== except) setSubmenuOpen(button, false);
      });
    }

    toggle.addEventListener("click", function () {
      setOpen(!nav.classList.contains("is-open"));
    });

    // Tapping a destination closes the panel so the page is visible on arrival.
    nav.addEventListener("click", function (event) {
      if (event.target.closest("a")) {
        setOpen(false);
        if (!desktopNav.matches) closeSubmenus();
      }
    });

    // Escape and taps outside the masthead dismiss the menu.
    document.addEventListener("keydown", function (event) {
      if (event.key === "Escape") {
        setOpen(false);
        closeSubmenus();
      }
    });
    document.addEventListener("click", function (event) {
      if (
        nav.classList.contains("is-open")
        && !event.target.closest("[data-global-masthead]")
      ) {
        setOpen(false);
      }
      if (!event.target.closest("[data-global-masthead]")) closeSubmenus();
    });

    // Returning to a wide viewport must never leave the page with a hidden nav.
    desktopNav.addEventListener("change", function (event) {
      if (event.matches) setOpen(false);
    });

    nav.querySelectorAll(".nav-item__disclosure").forEach(function (btn) {
      btn.addEventListener("click", function (event) {
        event.preventDefault();
        var item = btn.closest(".nav-item--menu");
        if (!item) return;
        var open = !item.classList.contains("is-open");
        closeSubmenus(btn);
        setSubmenuOpen(btn, open);
      });
    });
  }

  function initProgrammeDirectories() {
    document.querySelectorAll("[data-programme-directory]").forEach(function (directory) {
      var search = directory.querySelector("[data-programme-search]");
      var levelRoute = directory.querySelector("[data-programme-level-route]");
      var discipline = directory.querySelector("[data-programme-discipline]");
      var cards = Array.from(directory.querySelectorAll("[data-programme-card]"));
      var count = directory.querySelector("[data-programme-count]");
      var empty = directory.querySelector("[data-programme-empty]");
      var selectedCount = directory.querySelector("[data-programme-selected-count]");
      var compare = directory.querySelector("[data-programme-compare]");
      var clear = directory.querySelector("[data-programme-clear]");
      var comparison = directory.querySelector("[data-programme-comparison]");
      var comparisonGrid = directory.querySelector("[data-programme-comparison-grid]");
      if (!search || !discipline || cards.length === 0) return;

      function update() {
        var query = search.value.trim().toLocaleLowerCase();
        var selectedDiscipline = discipline.value;
        var visible = 0;
        cards.forEach(function (card) {
          var matchesQuery = !query || card.dataset.search.indexOf(query) !== -1;
          var matchesDiscipline =
            !selectedDiscipline || card.dataset.discipline === selectedDiscipline;
          var show = matchesQuery && matchesDiscipline;
          card.hidden = !show;
          if (show) visible += 1;
        });
        if (count) {
          count.textContent = visible + " " + (visible === 1 ? "programme" : "programmes");
        }
        if (empty) empty.hidden = visible !== 0;
      }

      function selectedCards() {
        return cards.filter(function (card) {
          var checkbox = card.querySelector("[data-programme-select]");
          return checkbox && checkbox.checked;
        });
      }

      function updateSelection() {
        var selected = selectedCards().length;
        if (selectedCount) selectedCount.textContent = selected + " selected";
        if (compare) compare.disabled = selected === 0;
        if (clear) clear.disabled = selected === 0;
        if (selected === 0 && comparison) comparison.hidden = true;
      }

      function renderComparison() {
        if (!comparison || !comparisonGrid) return;
        comparisonGrid.replaceChildren();
        selectedCards().forEach(function (card) {
          var article = document.createElement("article");
          var title = document.createElement("h3");
          var facts = document.createElement("p");
          var summary = document.createElement("p");
          var link = document.createElement("a");
          title.textContent = card.dataset.title;
          facts.textContent = [
            card.dataset.level,
            card.dataset.discipline,
            card.dataset.duration,
          ].filter(Boolean).join(" · ");
          summary.textContent = card.dataset.summary;
          link.href = card.dataset.href;
          link.textContent = "Programme details";
          article.append(title, facts, summary, link);
          comparisonGrid.append(article);
        });
        comparison.hidden = false;
        var heading = comparison.querySelector("h2");
        if (heading) heading.focus();
      }

      if (levelRoute) {
        levelRoute.addEventListener("change", function () {
          window.location.assign(levelRoute.value);
        });
      }
      search.addEventListener("input", update);
      discipline.addEventListener("change", update);
      cards.forEach(function (card) {
        var checkbox = card.querySelector("[data-programme-select]");
        if (checkbox) checkbox.addEventListener("change", updateSelection);
      });
      if (compare) compare.addEventListener("click", renderComparison);
      if (clear) {
        clear.addEventListener("click", function () {
          cards.forEach(function (card) {
            var checkbox = card.querySelector("[data-programme-select]");
            if (checkbox) checkbox.checked = false;
          });
          if (comparison) comparison.hidden = true;
          updateSelection();
        });
      }
    });
  }

  function storedTheme() {
    try {
      var value = window.localStorage.getItem(storageKey);
      return value === "light" || value === "dark" ? value : "";
    } catch (_error) {
      return "";
    }
  }

  function currentTheme() {
    return root.getAttribute("data-theme") === "dark" ? "dark" : "light";
  }

  function preferredTheme() {
    return storedTheme() || (media.matches ? "dark" : "light");
  }

  function applyTheme(theme) {
    if (theme === "dark") root.setAttribute("data-theme", "dark");
    else root.setAttribute("data-theme", "light");

    document.querySelectorAll("[data-theme-toggle]").forEach(function (button) {
      var dark = theme === "dark";
      button.setAttribute("aria-pressed", String(dark));
      button.setAttribute("aria-label", dark ? "Switch to light mode" : "Switch to dark mode");
      button.title = dark ? "Switch to light mode" : "Switch to dark mode";
    });
  }

  function toggleTheme() {
    var next = currentTheme() === "dark" ? "light" : "dark";
    try {
      window.localStorage.setItem(storageKey, next);
    } catch (_error) {
      // The selected theme still applies to the current page.
    }
    applyTheme(next);
  }

  installInstitutionalLockup();
  installInstitutionalNavigation();

  function initPage() {
    applyTheme(preferredTheme());
    document.querySelectorAll("[data-theme-toggle]").forEach(function (button) {
      button.addEventListener("click", toggleTheme);
    });
    initMobileNav();
    initProgrammeDirectories();
  }

  // Some pages load this shared file late while others defer it from <head>.
  // Initialise correctly in both cases so the same masthead always behaves alike.
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initPage, { once: true });
  } else {
    initPage();
  }

  function followDeviceTheme(event) {
    if (!storedTheme()) applyTheme(event.matches ? "dark" : "light");
  }

  if (typeof media.addEventListener === "function") {
    media.addEventListener("change", followDeviceTheme);
  } else if (typeof media.addListener === "function") {
    media.addListener(followDeviceTheme);
  }
})();

/* ------------------------------------------------------------------ *
 * Global masthead dropdowns — 2-level cascading hover-intent
 * (extended for fly-outs 2026-07-25).
 * Level 1: entering a top item opens its single-column dropdown; it
 * closes ~240ms after the pointer leaves BOTH the trigger and its
 * panel, so a diagonal move into the wider panel never slams it shut.
 * Level 2: a `.nav-subitem--menu` row opens a `.nav-flyout` beside it —
 * to the right, or to the LEFT when it would clip the viewport edge.
 * The fly-out is a DOM descendant of its row, so moving into it keeps
 * the pointer inside the row; a close-delay covers the brief transit,
 * and taking over a sibling fly-out is intent-delayed so a diagonal
 * sweep toward the open panel is never hijacked by rows passed along
 * the way. `.is-open` stays the single source of truth (no raw `:hover`
 * opener that would diagonal-close), matching the CSS reveal rules.
 * Desktop pointers only; touch/mobile use the click accordion — the ▸
 * disclosure toggles the nested fly-out in place. Idempotent, so it is
 * safe to load once per page.
 * ------------------------------------------------------------------ */
(function () {
  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }
  ready(function () {
    if (document.documentElement.hasAttribute("data-nav-hover-intent")) return;
    document.documentElement.setAttribute("data-nav-hover-intent", "1");

    var desktop = window.matchMedia("(min-width: 768px)");
    var items = Array.prototype.slice.call(
      document.querySelectorAll("[data-global-masthead] .nav-item--menu")
    );
    if (!items.length) return;

    var CLOSE_DELAY = 240;           // level-1 close delay
    var FLYOUT_CLOSE_DELAY = 300;    // level-2 close delay — covers diagonal transit
    var FLYOUT_SWITCH_DELAY = 140;   // delay before a sibling fly-out takes over
    var timers = new WeakMap();      // level-1 close timers
    var closeTimers = new WeakMap(); // level-2 close timers
    var openTimers = new WeakMap();  // level-2 switch-intent timers

    function subitemsOf(item) {
      return Array.prototype.slice.call(
        item.querySelectorAll(".nav-subitem--menu")
      );
    }

    function setSubOpen(sub, open) {
      sub.classList.toggle("is-open", open);
      var disc = sub.querySelector(":scope > .nav-subitem__disclosure");
      if (disc) disc.setAttribute("aria-expanded", String(open));
    }

    function closeSub(sub) {
      clearTimeout(openTimers.get(sub));
      clearTimeout(closeTimers.get(sub));
      setSubOpen(sub, false);
    }

    function closeSiblingSubs(item, except) {
      subitemsOf(item).forEach(function (s) { if (s !== except) closeSub(s); });
    }

    // Right by default; flip to the LEFT (and point the chevron left) when the
    // panel would otherwise clip past the viewport's right edge.
    function placeFlyout(sub) {
      var fly = sub.querySelector(":scope > .nav-flyout");
      if (!fly) return;
      fly.classList.remove("nav-flyout--left");
      sub.classList.remove("is-flipped");
      if (!desktop.matches) return;                // mobile fly-outs are static
      var rect = fly.getBoundingClientRect();
      if (rect.right > document.documentElement.clientWidth - 6) {
        fly.classList.add("nav-flyout--left");
        sub.classList.add("is-flipped");
      }
    }

    function openSub(sub) {
      var item = sub.closest(".nav-item--menu");
      clearTimeout(openTimers.get(sub));
      clearTimeout(closeTimers.get(sub));
      if (item) closeSiblingSubs(item, sub);          // one fly-out per menu
      setSubOpen(sub, true);
      placeFlyout(sub);
    }

    function scheduleCloseSub(sub) {
      clearTimeout(closeTimers.get(sub));
      closeTimers.set(
        sub,
        setTimeout(function () { setSubOpen(sub, false); }, FLYOUT_CLOSE_DELAY)
      );
    }

    function closeAll(except) {
      items.forEach(function (it) {
        if (it !== except) {
          clearTimeout(timers.get(it));
          it.classList.remove("is-open");
          subitemsOf(it).forEach(closeSub);           // reset nested fly-outs too
        }
      });
    }

    function openItem(item) {
      if (!desktop.matches) return;
      clearTimeout(timers.get(item));
      closeAll(item);                                 // one menu open at a time
      item.classList.add("is-open");
    }

    items.forEach(function (item) {
      function open() { openItem(item); }
      function scheduleClose() {
        if (!desktop.matches) return;
        clearTimeout(timers.get(item));
        timers.set(item, setTimeout(function () {
          item.classList.remove("is-open");
          subitemsOf(item).forEach(closeSub);
        }, CLOSE_DELAY));
      }
      // Pointer: mouseleave does not fire while the pointer is over the panel
      // (a DOM descendant), so the menu stays open over it; the delay covers
      // the brief off-element transit in between.
      item.addEventListener("mouseenter", open);
      item.addEventListener("mouseleave", scheduleClose);
      // Keyboard parity: focus opens, focus leaving the item closes.
      item.addEventListener("focusin", open);
      item.addEventListener("focusout", function (event) {
        if (
          desktop.matches
          && !item.contains(event.relatedTarget)
          && !item.matches(":hover")
        ) {
          item.classList.remove("is-open");
          subitemsOf(item).forEach(closeSub);
        }
      });

      // ---- level-2 cascading fly-outs within this menu ----
      subitemsOf(item).forEach(function (sub) {
        sub.addEventListener("mouseenter", function () {
          if (!desktop.matches) return;
          clearTimeout(closeTimers.get(sub));         // cancel our own close
          if (sub.classList.contains("is-open")) return;
          var siblingOpen = subitemsOf(item).some(function (s) {
            return s !== sub && s.classList.contains("is-open");
          });
          if (siblingOpen) {
            // A fly-out is already open: delay the switch so a diagonal sweep
            // toward it is not hijacked by rows crossed along the way.
            clearTimeout(openTimers.get(sub));
            openTimers.set(
              sub,
              setTimeout(function () { openSub(sub); }, FLYOUT_SWITCH_DELAY)
            );
          } else {
            openSub(sub);                             // first open is instant
          }
        });
        sub.addEventListener("mouseleave", function () {
          if (!desktop.matches) return;
          clearTimeout(openTimers.get(sub));          // drop a pending switch
          scheduleCloseSub(sub);
        });
        sub.addEventListener("focusin", function () {
          if (!desktop.matches) return;
          clearTimeout(closeTimers.get(sub));
          openSub(sub);
        });
        sub.addEventListener("focusout", function (event) {
          if (
            desktop.matches
            && !sub.contains(event.relatedTarget)
            && !sub.matches(":hover")
          ) {
            closeSub(sub);
          }
        });
        // Mobile: the ▸ disclosure toggles the nested fly-out in place without
        // following the row link. Desktop keeps hover as the single opener.
        var disc = sub.querySelector(":scope > .nav-subitem__disclosure");
        if (disc) {
          disc.addEventListener("click", function (event) {
            if (desktop.matches) return;
            event.preventDefault();
            event.stopPropagation();
            var willOpen = !sub.classList.contains("is-open");
            closeSiblingSubs(item, sub);
            setSubOpen(sub, willOpen);
          });
        }
      });
    });

    // History restoration can resume a document without firing mouseenter.
    // Reconcile `.is-open` with the pointer after each initial load / BFCache
    // return so a restored menu is neither stale nor inert.
    window.addEventListener("pageshow", function () {
      window.requestAnimationFrame(function () {
        if (!desktop.matches) return;
        var hovered = items.find(function (item) {
          return item.matches(":hover");
        });
        if (hovered) openItem(hovered);
        else closeAll(null);
      });
    });

    // Click outside the masthead, or Escape, dismisses any open menu.
    document.addEventListener("click", function (event) {
      if (!event.target.closest("[data-global-masthead]")) closeAll(null);
    });
    document.addEventListener("keydown", function (event) {
      if (event.key === "Escape") closeAll(null);
    });
    // Crossing below the desktop breakpoint clears desktop open-state so the
    // mobile panel never inherits a stuck-open submenu.
    desktop.addEventListener("change", function (event) {
      if (!event.matches) closeAll(null);
    });
  });
})();
