// Generated from MIT-WPU public department and faculty records.
// Classification reflects published evidence and remains editable.
window.SCIENCE_FACULTY = {
  "physics": [
    {
      "id": "deobrat-singh",
      "hrEmployeeId": "",
      "publicSourceSlug": "deobrat-singh",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Deobrat Singh",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "High-energy theory, gravitation, and fundamental interactions.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Deobrat%20Singh.webp",
      "photoPath": "assets/people/deobrat-singh.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/deobrat-singh",
        "scholar": "https://scholar.google.com/citations?user=aRAErjsAAAAJ&hl=en",
        "scopus": "http://www.scopus.com/inward/authorDetails.url?authorID=57198856954&partnerID=MN8TOARS",
        "orcid": "https://orcid.org/0000-0003-0425-3243"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "sachin-arun-kulkarni",
      "hrEmployeeId": "",
      "publicSourceSlug": "sachin-arun-kulkarni",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Sachin Arun Kulkarni",
      "designation": "Associate Professor & Head of Department",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Nanomaterials and nanocomposites: synthesis, characterisation, and applications.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Sachin%20Arun%20Kulkarni.webp",
      "photoPath": "assets/people/sachin-arun-kulkarni.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/sachin-arun-kulkarni",
        "orcid": "https://orcid.org/0000-0002-9490-1883",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=58075980100",
        "scholar": "https://scholar.google.com/citations?user=cNJ_0GwAAAAJ&hl=en"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "shital-vasant-kahane",
      "hrEmployeeId": "",
      "publicSourceSlug": "shital-vasant-kahane",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Shital Vasant Kahane",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Metal–semiconductor quantum dots and nanomaterials for optoelectronic, energy-storage, and biological applications.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Shital%20Vasant%20Kahane.webp",
      "photoPath": "assets/people/shital-vasant-kahane.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/shital-vasant-kahane",
        "scholar": "https://scholar.google.com/citations?user=Ec6ychUAAAAJ&hl=en&authuser=1",
        "orcid": "https://orcid.org/0000-0002-9556-1868"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "narendra-laxman-mathakari",
      "hrEmployeeId": "",
      "publicSourceSlug": "narendra-laxman-mathakari",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Narendra Laxman Mathakari",
      "designation": "Professor of Practice",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Radiation processing of polymers and composites; viscoelastic and acoustic properties of liquid mixtures.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643cf876198371681717366.jpg",
      "photoPath": "assets/people/narendra-laxman-mathakari.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/narendra-laxman-mathakari",
        "orcid": "https://orcid.org/0000-0003-3195-9700",
        "scholar": "https://scholar.google.com/citations?user=TJS3VsIAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=23098452200"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "ajit-baburao-deore",
      "hrEmployeeId": "",
      "publicSourceSlug": "ajit-baburao-deore",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Ajit Baburao Deore",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Corrosion science, including anti-corrosive films on steel.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e5597382f61681806743.jpg",
      "photoPath": "assets/people/ajit-baburao-deore.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/ajit-baburao-deore"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "jagadish-hammu-naik",
      "hrEmployeeId": "",
      "publicSourceSlug": "jagadish-hammu-naik",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Jagadish Hammu Naik",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Dielectrics and spectroscopy; structural and physical properties of particulate-filled polymers.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e40e7a2c961681801447.jpg",
      "photoPath": "assets/people/jagadish-hammu-naik.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/jagadish-hammu-naik",
        "scholar": "https://scholar.google.com/citations?hl=en&user=LPN9TuAAAAAJ&view_op=list_works&sortby=pubdate",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=56225585900"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "prasantakumar-sudarshan-ghosh",
      "hrEmployeeId": "",
      "publicSourceSlug": "prasantakumar-sudarshan-ghosh",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. PrasantaKumar Sudarshan Ghosh",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Organic and inorganic functional nanomaterials, organic field-effect transistors, hybrid materials, chemical sensors, and research instrumentation.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/6437ab84367a21681369988.jpg",
      "photoPath": "assets/people/prasantakumar-sudarshan-ghosh.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/prasantakumar-sudarshan-ghosh",
        "scholar": "https://scholar.google.com/citations?user=Qhnz_wIAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=56388157800",
        "orcid": "https://orcid.org/0000-0001-5680-1673"
      },
      "photoWidth": 468,
      "photoHeight": 473
    },
    {
      "id": "aavishkar-chittaranjan-katti",
      "hrEmployeeId": "",
      "publicSourceSlug": "aavishkar-chittaranjan-katti",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Aavishkar Chittaranjan Katti",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Theoretical nonlinear optics, nonlinear dynamics, optical solitons, and photonic systems.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643798bda8e821681365181.jpg",
      "photoPath": "assets/people/aavishkar-chittaranjan-katti.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/aavishkar-chittaranjan-katti",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57191970629",
        "scholar": "https://scholar.google.co.in/citations?user=NVdkslgAAAAJ&hl=en&oi=ao"
      },
      "photoWidth": 468,
      "photoHeight": 473
    },
    {
      "id": "apurv-chaitanya-nellikka",
      "hrEmployeeId": "",
      "publicSourceSlug": "apurv-chaitanya-nellikka",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Apurv Chaitanya Nellikka",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Experimental nonlinear and quantum optics, structured light, and nanophotonics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Apurv-Nellikka.webp",
      "photoPath": "assets/people/apurv-chaitanya-nellikka.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/apurv-chaitanya-nellikka",
        "orcid": "https://orcid.org/0000-0002-0516-7200",
        "scholar": "https://scholar.google.com/citations?user=rQh89TsAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=56210838000"
      },
      "photoWidth": 468,
      "photoHeight": 473
    },
    {
      "id": "rahul-ashokrao-aher",
      "hrEmployeeId": "",
      "publicSourceSlug": "rahul-ashokrao-aher",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Rahul Ashokrao Aher",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Semiconductor nanostructures, two-dimensional materials, thin films, sensors, and optoelectronic devices.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e4117466341681801495.jpg",
      "photoPath": "assets/people/rahul-ashokrao-aher.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/rahul-ashokrao-aher",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57225239893"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "anagha-sudhir-karne",
      "hrEmployeeId": "",
      "publicSourceSlug": "anagha-sudhir-karne",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Anagha Sudhir Karne",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Soft matter physics, quantum chemistry, quantum computing, and computational physics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/6437aa1b972d41681369627.jpg",
      "photoPath": "assets/people/anagha-sudhir-karne.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/anagha-sudhir-karne",
        "scholar": "https://scholar.google.com/citations?user=4uTr0aQtXEsC&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=55875374200",
        "orcid": "https://orcid.org/0000-0002-3053-0235"
      },
      "photoWidth": 468,
      "photoHeight": 473
    },
    {
      "id": "debabrata-saha",
      "hrEmployeeId": "",
      "publicSourceSlug": "debabrata-saha",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Debabrata Saha",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Semiconductor, ferroelectric, and dielectric thin films for solid-state devices, including photodetectors and thin-film transistors.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e41556d4f31681801557.jpg",
      "photoPath": "assets/people/debabrata-saha.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/debabrata-saha",
        "orcid": "https://orcid.org/0000-0001-6469-6391",
        "scholar": "https://scholar.google.com/citations?user=TBgCfg0AAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=55828097100"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "raju-shivaji-ingale",
      "hrEmployeeId": "",
      "publicSourceSlug": "raju-shivaji-ingale",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Raju Shivaji Ingale",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Metal-oxide and nanocomposite thick and thin films for gas sensing.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643cf8971b3a21681717399.jpg",
      "photoPath": "assets/people/raju-shivaji-ingale.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/raju-shivaji-ingale",
        "orcid": "https://orcid.org/0000-0002-1195-8092",
        "scholar": "https://scholar.google.com/citations?hl=en&user=vW_99pMAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "abhijit-bendre",
      "hrEmployeeId": "",
      "publicSourceSlug": "abhijit-bendre",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Abhijit Bendre",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:57.382524+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Cosmic magnetic fields, nonlinear and galactic dynamos, the interstellar medium, and cosmic-ray dynamos.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Abijit-Bendre.webp",
      "photoPath": "assets/people/abhijit-bendre.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/abhijit-bendre",
        "scholar": "https://scholar.google.com/citations?user=hwwmIKcAAAAJ&hl=en&authuser=1",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=55600446700"
      },
      "photoWidth": 473,
      "photoHeight": 468
    }
  ],
  "chemistry": [
    {
      "id": "vasiahmed-ebrahim-shaikh",
      "hrEmployeeId": "",
      "publicSourceSlug": "vasiahmed-ebrahim-shaikh",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. VasiAhmed Ebrahim Shaikh",
      "designation": "Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Liquid-crystalline polymers, biopolymers, microplastics, water purification, and polymer chemistry.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/VasiAhmed-Ebrahim-Shaikh-img.webp",
      "photoPath": "assets/people/vasiahmed-ebrahim-shaikh.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/vasiahmed-ebrahim-shaikh",
        "orcid": "https://orcid.org/0000-0002-7502-570X",
        "scholar": "https://scholar.google.com/citations?user=qes29e8AAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=6507546181"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "kiran-kisan-kokate",
      "hrEmployeeId": "",
      "publicSourceSlug": "kiran-kisan-kokate",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Kiran Kisan Kokate",
      "designation": "Associate Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Kiran Kisanrao Kokate is an Associate Professor in Chemistry & acted as head for two years in the academic year 2021-22 & 2022-23. He has a teaching experience of 24 years. He has completed his PhD from Sant Gadge Baba Amravati University, Amravti and his area of interest includes conducting…",
      "research": "Conducting polymers and metal-oxide nanocomposites, including PEDOT/ZnO materials.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Kiran%20Kisan%20Kokate.webp",
      "photoPath": "assets/people/kiran-kisan-kokate.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/kiran-kisan-kokate"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "meghana-ganesh-gote",
      "hrEmployeeId": "",
      "publicSourceSlug": "meghana-ganesh-gote",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Meghana Ganesh Gote",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Meghana Gote earned her PhD from the University of Mumbai, specializing in ionic liquids. With approximately 15 years of academic experience, she now serves as the Program Director for the Department of Chemistry. Dr. Gote possesses extensive practical knowledge in synthetic organic chemistry…",
      "research": "Synthetic organic chemistry, catalysis, water remediation, and asymmetric synthesis.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Meghna%20Ganesh%20Gote.webp",
      "photoPath": "assets/people/meghana-ganesh-gote.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/meghana-ganesh-gote",
        "scholar": "https://scholar.google.com/citations?user=1g7FYW8AAAAJ&hl=en",
        "scopus": "https://www.scopus.com/inward/authorDetails.url?authorID=8632924000&partnerID=MN8TOARS",
        "orcid": "https://orcid.org/0000-0002-7862-9621"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "vandana-aryan-mooss",
      "hrEmployeeId": "",
      "publicSourceSlug": "vandana-aryan-mooss",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Vandana Aryan Mooss",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Vandana A. Mooss is an Assistant professor at Department of Chemistry, MIT World Peace University with 8 years of research and 3 years of teaching experience. She is involved in teaching various course at the Department of chemistry such as physical chemistry, inorganic chemistry, polymer…",
      "research": "Conducting polymers, nanocomposites, protective coatings, biodegradable polymers, and packaging applications.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Vandana%20Aryan%20Mooss.webp",
      "photoPath": "assets/people/vandana-aryan-mooss.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/vandana-aryan-mooss",
        "scholar": "https://scholar.google.com/citations?user=sRiD7RwAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57191201665",
        "orcid": "https://orcid.org/0000-0002-5499-9097"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "sanjay-babanrao-bhagwat",
      "hrEmployeeId": "",
      "publicSourceSlug": "sanjay-babanrao-bhagwat",
      "recordSource": "mitwpu-public-site",
      "name": "Mr. Sanjay Babanrao Bhagwat",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Sanjay Bhagwat is currently working as an Assistant Professor in the Department of Chemistry at MIT World Peace University (MIT-WPU) in Pune, India. He completed his M.Sc. in Organic Chemistry from Fergusson College, Pune. He qualified CSIR National Eligibility Test (NET) in Chemical Science with…",
      "research": "Environmental chemistry, wastewater treatment, and materials chemistry.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643cf6dbc0e5e1681716955.jpg",
      "photoPath": "assets/people/sanjay-babanrao-bhagwat.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/sanjay-babanrao-bhagwat",
        "scholar": "https://scholar.google.com/citations?user=jGWsIP0AAAAJ&hl=en&authuser=1"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "vaishali-hanumant-gaikwad",
      "hrEmployeeId": "",
      "publicSourceSlug": "vaishali-hanumant-gaikwad",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Vaishali Hanumant Gaikwad",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Vaishali Gaikwad has a ph.d in Inorganic Chemistry with a focus on metal complexes for the improvement of drugs function and a Master’s degree in Organic chemistry. She has qualified CSIR -NET in 2007",
      "research": "Doctoral research in inorganic chemistry focused on metal complexes and drug function.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Vaishali%20Gaikwad.webp",
      "photoPath": "assets/people/vaishali-hanumant-gaikwad.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/vaishali-hanumant-gaikwad"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "dev-kumar-thapa",
      "hrEmployeeId": "",
      "publicSourceSlug": "dev-kumar-thapa",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Dev Kumar Thapa",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dev Kumar Thapa currently serves as an assistant professor in the Department of Chemistry at MIT-WPU, a position he has held since October 2023. Before joining MIT-WPU, he held the position of assistant professor at SRM University Sikkim",
      "research": "Nanomaterial synthesis, plasmonics, metamaterials, nanophotonics, and single-particle spectroscopy and microscopy.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Devkumar-Thapa.webp",
      "photoPath": "assets/people/dev-kumar-thapa.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/dev-kumar-thapa",
        "scholar": "https://scholar.google.com/citations?user=kUXHgjAAAAAJ&hl=en"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "soumava-biswas",
      "hrEmployeeId": "",
      "publicSourceSlug": "soumava-biswas",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Soumava Biswas",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Soumava Biswas obtained his PhD in chemistry from IISER Bhopal, India under the supervision of Professor Sanjit Konar in 2017. Then he worked with the research group of Prof. Masahiro Yamashita, at Tohoku University, Japan as a JSPS postdoctoral fellow for two years",
      "research": "Metal-organic frameworks for gas storage and carbon capture, molecular nanomagnets, spin-crossover switches, and fluorescent sensors.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Soumava_Biswas.webp",
      "photoPath": "assets/people/soumava-biswas.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/soumava-biswas",
        "orcid": "https://orcid.org/0000-0003-0107-7264",
        "scholar": "https://scholar.google.co.in/citations?user=CU2b_t0AAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=55598984000"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "parineeta-das",
      "hrEmployeeId": "",
      "publicSourceSlug": "parineeta-das",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Parineeta Das",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:08.842268+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Parineeta Das has completed her doctoral study at National Institute of Technology Nagaland (NIT Nagaland). Her doctoral study focused on dendrimers, the emerging polymeric architectures having several interesting features suitable for application in many diverse fields including biomedical…",
      "research": "Polymer science, biopolymers, biocatalysis, dendrimers, green synthesis, anticorrosive coatings, biodiesel, and computational toxicology.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Parineeta%20Das.webp",
      "photoPath": "assets/people/parineeta-das.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/parineeta-das",
        "scholar": "https://scholar.google.com/citations?hl=en&user=P0S3QZAAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    }
  ],
  "mathematics": [
    {
      "id": "mukesh-kumar-pal",
      "hrEmployeeId": "",
      "publicSourceSlug": "mukesh-kumar-pal",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Mukesh Kumar Pal",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Mukesh Kumar Pal is an Assistant Professor of Mathematics, specializing in Applied Mathematics. He is currently affiliated with the Department of Mathematics & Statistics at MIT-World Peace University, Kothrud, Pune, Maharashtra-411038, India",
      "research": "Mathematical modelling of smart materials, elastodynamics, and wave propagation.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Mukesh%20Kumar%20Pal.webp",
      "photoPath": "assets/people/mukesh-kumar-pal.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/mukesh-kumar-pal",
        "scholar": "https://scholar.google.com/citations?user=N2hkcH8AAAAJ&hl=en"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "rupal-chandulal-shroff",
      "hrEmployeeId": "",
      "publicSourceSlug": "rupal-chandulal-shroff",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Rupal Chandulal Shroff",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "View the profile of MIT-WPU committed faculty member Ms. Rupal Chandulal Shroff. Find out about her knowledge, academic successes, and efforts toward student growth and educational greatness",
      "research": "Algebra, lattice theory, graph theory, and discrete mathematics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Rupal%20Chandulal%20Shroff.webp",
      "photoPath": "assets/people/rupal-chandulal-shroff.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/rupal-chandulal-shroff",
        "orcid": "https://orcid.org/0000-0002-5258-9107",
        "scholar": "https://scholar.google.co.in/citations?hl=en&user=T1B8k1kAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "prashant-pralhad-malavadkar",
      "hrEmployeeId": "",
      "publicSourceSlug": "prashant-pralhad-malavadkar",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Prashant Pralhad Malavadkar",
      "designation": "Professor & Program Director",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Prashant P. Malavadkar is Professor and Head of the mathematics and statistics department of Dr. Vishwanath Karad MIT-World Peace University in Pune, India. He has a Ph.D. in mathematics, as well as M.Sc., SET, and M.Phil. degree",
      "research": "Matroid theory, graph theory, combinatorics, and discrete mathematics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Dr.Prashant_Malavadkar_Photo.webp",
      "photoPath": "assets/people/prashant-pralhad-malavadkar.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/prashant-pralhad-malavadkar",
        "orcid": "https://orcid.org/0000-0001-7706-3286",
        "scholar": "https://scholar.google.com/citations?user=r4Xog48AAAAJ",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=37056044300"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "priyanka-kumari",
      "hrEmployeeId": "",
      "publicSourceSlug": "priyanka-kumari",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Priyanka Kumari",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Priyanka Kumari is currently working as an Assistant Professor in Department of Mathematics and Statistics, Dr Vishwanath Karad MIT World Peace University, Pune. Dr Priyanka Kumari holds a Doctorate in Mathematics (Algebraic Combinatorics) from Birla Institute of Technology and Science Pilani…",
      "research": "Algebraic combinatorics, combinatorial designs, difference sets, and Boolean bent functions.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Priyanka%20Kumari.webp",
      "photoPath": "assets/people/priyanka-kumari.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/priyanka-kumari",
        "orcid": "https://orcid.org/0000-0003-4453-8518",
        "scholar": "https://scholar.google.com/citations?user=wscF198AAAAJ",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57660659400"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "umeshkumar-bhaiyalal-dubey",
      "hrEmployeeId": "",
      "publicSourceSlug": "umeshkumar-bhaiyalal-dubey",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Umeshkumar Bhaiyalal Dubey",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Umesh Kumar Bhayyalal Dubey is a highly accomplished researcher and academician with an extensive educational background, including two PhDs and two MBA degrees. With over 15 years of teaching experience, Dr. Dubey has authored multiple books, including",
      "research": "Statistical analysis, research methodology, and business and management applications.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e2ece48d921681796814.jpg",
      "photoPath": "assets/people/umeshkumar-bhaiyalal-dubey.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/umeshkumar-bhaiyalal-dubey",
        "orcid": "https://orcid.org/0000-0003-1241-7332",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57203638756",
        "scholar": "https://scholar.google.com/citations?user=tJLzPh0AAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "veena-pravin-kshirsagar",
      "hrEmployeeId": "",
      "publicSourceSlug": "veena-pravin-kshirsagar",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Veena Pravin Kshirsagar",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "unverified",
      "summary": "",
      "research": "",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Veena-Kshirsagar.webp",
      "photoPath": "assets/people/veena-pravin-kshirsagar.webp",
      "links": {},
      "photoWidth": 270,
      "photoHeight": 267
    },
    {
      "id": "akilbasha-a",
      "hrEmployeeId": "",
      "publicSourceSlug": "akilbasha-a",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Akilbasha A",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. A. Akilbasha is a highly educated individual who holds a Ph.D., M.Phil., M.Sc., B.Ed., and B.Sc. in Mathematics from premier institutions. He has 18 publications, including 18 research articles and 5 manuscripts that are currently under review in Impact Factor Journals, in the areas of Supply…",
      "research": "Optimisation, decision-making, logistics and supply-chain models, fuzzy and rough sets, and fluid dynamics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e3019176931681797145.jpg",
      "photoPath": "assets/people/akilbasha-a.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/akilbasha-a",
        "orcid": "https://orcid.org/0000-0001-6914-0667",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=56940684100",
        "scholar": "https://scholar.google.co.in/citations?user=Ebq28Z8AAAAJ&hl=en"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "abdul-nasir-khan",
      "hrEmployeeId": "",
      "publicSourceSlug": "abdul-nasir-khan",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Abdul Nasir Khan",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Abdul Nasir Khan is an Assistant Professor in the School of Mathematics and Statistics at MIT World Peace University. He completed his M.Sc. in Statistics in 2015 from Aligarh Muslim University, Aligarh, and subsequently pursued his PhD at the same university, which he completed in 2021",
      "research": "Ordered random variables, Bayesian inference, parameter estimation, and biostatistics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e3fedd91a91681801197.jpg",
      "photoPath": "assets/people/abdul-nasir-khan.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/abdul-nasir-khan",
        "scholar": "https://scholar.google.com/citations?user=0XaX0u0AAAAJ",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57219130406",
        "orcid": "https://orcid.org/0000-0002-5260-7555"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "gajanan-malleshi-birajdar",
      "hrEmployeeId": "",
      "publicSourceSlug": "gajanan-malleshi-birajdar",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Gajanan Malleshi Birajdar",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Gajanan Birajdar is an Assistant Professor of Mathematics and Statistics with expertise in Geometric Function Theory. He obtained his Master's degree in Mathematics from Shivaji University, Kolhapur, and is currently pursuing his Ph.D. in Complex Analysis from the same university",
      "research": "Geometric function theory and univalent functions.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/64424bb37c06b1682066355.jpg",
      "photoPath": "assets/people/gajanan-malleshi-birajdar.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/gajanan-malleshi-birajdar",
        "scholar": "https://scholar.google.com/citations?user=Qa61X3sAAAAJ",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57732563500",
        "orcid": "https://orcid.org/0000-0002-1915-921X"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "amol-prakash-narke",
      "hrEmployeeId": "",
      "publicSourceSlug": "amol-prakash-narke",
      "recordSource": "mitwpu-public-site",
      "name": "Mr. Amol Prakash Narke",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Mr. Amol Narke holds an M.Sc in Mathematics and has qualified the State Eligibility Test (SET) in Mathematics. With seven years of teaching experience, his research interests lie in Graph Theory and Matroid Theory",
      "research": "Graph theory, discrete mathematics, and combinatorics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Amol-Narke.webp",
      "photoPath": "assets/people/amol-prakash-narke.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/amol-prakash-narke"
      },
      "photoWidth": 473,
      "photoHeight": 469
    },
    {
      "id": "kundan-ramesh-nagare",
      "hrEmployeeId": "",
      "publicSourceSlug": "kundan-ramesh-nagare",
      "recordSource": "mitwpu-public-site",
      "name": "Mr. Kundan Ramesh Nagare",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Prof. Kundan R. Nagare is an Assistant Professor at MIT-WPU, who completed her post-graduation in Mathematics from SPPU in 2015. In 2016, she cleared the State Eligibility Test (SET) examination and started her teaching career as an Assistant Professor at MIT-WPU in 2017",
      "research": "Matroid theory.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Kundan-Nagare.webp",
      "photoPath": "assets/people/kundan-ramesh-nagare.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/kundan-ramesh-nagare"
      },
      "photoWidth": 270,
      "photoHeight": 267
    },
    {
      "id": "vaishali-manish-joshi",
      "hrEmployeeId": "",
      "publicSourceSlug": "vaishali-manish-joshi",
      "recordSource": "mitwpu-public-site",
      "name": "Mrs. Vaishali Manish Joshi",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Prof. Vaishali M Joshi is working as an Assistant Professor in the department of Mathematics and Statistics at Dr. Vishwanath Karad MIT World Peace University in Pune, India. She has a 22 yrars of teaching exprience . She has joined MIT in the year 2012 and completed successfully 11 years of…",
      "research": "Lattice theory, graph theory, and algebra.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643cfda3426981681718691.jpg",
      "photoPath": "assets/people/vaishali-manish-joshi.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/vaishali-manish-joshi"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "pratibha-sharad-kshirsagar",
      "hrEmployeeId": "",
      "publicSourceSlug": "pratibha-sharad-kshirsagar",
      "recordSource": "mitwpu-public-site",
      "name": "Mrs. Pratibha Sharad Kshirsagar",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "unverified",
      "summary": "",
      "research": "",
      "email": "",
      "photoSource": "",
      "photoPath": "",
      "links": {}
    },
    {
      "id": "sachin-shivaji-gunjal",
      "hrEmployeeId": "",
      "publicSourceSlug": "sachin-shivaji-gunjal",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Sachin Shivaji Gunjal",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Mr. Sachin Gunjal holds a Master's degree in Mathematics and has qualified the State Eligibility Test (SET). With seven years of teaching experience, he has secured the 8th rank across all colleges in T.Y.B.Sc. under SPPU and the 2nd rank at M.Sc.(Maths) in SPPU",
      "research": "Matroid theory, algebraic coding theory, and discrete mathematics.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/644251f47489e1682067956.jpg",
      "photoPath": "assets/people/sachin-shivaji-gunjal.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/sachin-shivaji-gunjal",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57372983000",
        "scholar": "https://scholar.google.com/citations?user=twkGytYAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "uday-vilas-jagadale",
      "hrEmployeeId": "",
      "publicSourceSlug": "uday-vilas-jagadale",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Uday Vilas Jagadale",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Graph theory, discrete mathematics, matroid theory, and connectivity of interconnection networks.",
      "email": "",
      "photoSource": "",
      "photoPath": "",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/uday-vilas-jagadale",
        "scholar": "https://scholar.google.com/citations?user=PLhaFl8AAAAJ",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57373004400",
        "orcid": "https://orcid.org/0000-0002-6707-7710"
      }
    },
    {
      "id": "rajashree-sahadeo-jadhav",
      "hrEmployeeId": "",
      "publicSourceSlug": "rajashree-sahadeo-jadhav",
      "recordSource": "mitwpu-public-site",
      "name": "Mrs. Rajashree Sahadeo Jadhav",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Prof. Rajashree S. Jadhav is working as an Assistant Professor in the department of Mathematics and Statistics at Dr. Vishwanath Karad MIT World Peace University in Pune, India. She has a 16 years of teaching experience. She has joined MIT in the year 2015 and completed successfully 9 years of…",
      "research": "Fractional differential equations and numerical analysis.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/6437a12ce11971681367340.jpg",
      "photoPath": "assets/people/rajashree-sahadeo-jadhav.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/rajashree-sahadeo-jadhav"
      },
      "photoWidth": 468,
      "photoHeight": 473
    },
    {
      "id": "suvarna-gopal-ranade",
      "hrEmployeeId": "",
      "publicSourceSlug": "suvarna-gopal-ranade",
      "recordSource": "mitwpu-public-site",
      "name": "Mrs. Suvarna Gopal Ranade",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "unverified",
      "summary": "Prof. Suvarna Ranade is working as an Assistant professor and program head of M.Sc. Statistics program of Department of Mathematics and Statistics at Dr. Vishwanath Karad MIT world Peace university. She has a vast experience of teaching in PG as well as UG",
      "research": "",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643cfd3be3e161681718587.jpg",
      "photoPath": "assets/people/suvarna-gopal-ranade.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/suvarna-gopal-ranade"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "abhishek-singh",
      "hrEmployeeId": "",
      "publicSourceSlug": "abhishek-singh",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Abhishek Singh",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Sampling, ranked-set sampling, statistical inference, quality control, time series, data science, and machine learning.",
      "email": "",
      "photoSource": "",
      "photoPath": "",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/abhishek-singh",
        "scholar": "https://scholar.google.com/citations?user=K6xNLtwAAAAJ",
        "orcid": "https://orcid.org/0000-0003-2009-5177"
      }
    },
    {
      "id": "ashok-kumar-jaiswal",
      "hrEmployeeId": "",
      "publicSourceSlug": "ashok-kumar-jaiswal",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Ashok Kumar Jaiswal",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "In December 2022, I proudly achieved a significant academic accomplishment by obtaining a Ph.D. in Statistics from the prestigious IIT (ISM) Dhanbad. I am now thrilled to be serving as an Assistant Professor at MIT WPU in Pune, where I can pursue my passion for teaching and research",
      "research": "Sampling theory, time-series analysis, big data, data science, and machine learning.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/64424a11533a11682065937.jpg",
      "photoPath": "assets/people/ashok-kumar-jaiswal.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/ashok-kumar-jaiswal",
        "scholar": "https://scholar.google.com/citations?user=IDp14JYAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "hemant-shripad-kulkarni",
      "hrEmployeeId": "",
      "publicSourceSlug": "hemant-shripad-kulkarni",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Hemant Shripad Kulkarni",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. Hemant Kulkarni is an Assistant Professor at Department of Mathemathics and Statistics, Dr. Vishwnath Karad, MIT World Peace University Since January 2023. He did his Ph.D in Statistics (Statistical Genetics) from Indian Statistical Institute, Kolkata in 2018. His areas reaserch is Statistical…",
      "research": "Statistical genetics, quantile regression, Bayesian computing, official statistics, and time-series analysis.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Hemant-Kulkarani.webp",
      "photoPath": "assets/people/hemant-shripad-kulkarni.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/hemant-shripad-kulkarni",
        "scholar": "https://scholar.google.com/citations?user=ga71KboAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "ramaa-ashish-sandu",
      "hrEmployeeId": "",
      "publicSourceSlug": "ramaa-ashish-sandu",
      "recordSource": "mitwpu-public-site",
      "name": "Mrs. Ramaa Ashish Sandu",
      "designation": "Associate Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Prof. Ramaa Sandu is working as an Associate Professor in the department of Mathematics and Statistics at Dr. Vishwanath Karad MIT World Peace University in Pune, India. She has a vast experience of teaching Engineering Mathematics since 1992 & completed 27 years in MIT",
      "research": "Differential equations and Laplace transforms.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Rama-Sandu.webp",
      "photoPath": "assets/people/ramaa-ashish-sandu.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/ramaa-ashish-sandu"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "mukund-gokhale",
      "hrEmployeeId": "",
      "publicSourceSlug": "mukund-gokhale",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Mukund Gokhale",
      "designation": "Professor Emeritus",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "Dr. M. Y. Gokhale is a distinguished Professor with a passion for mathematics and a wide range of research interests. Holding an M.Sc. in Maths and a Ph.D. degree, Dr. M. Y. Gokhale has established themselves as an expert in the field of Fluid Mechanics, Signal Processing, and Numerical Analysis",
      "research": "Fluid mechanics, signal processing, and numerical analysis.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Mukund-Gokhale.webp",
      "photoPath": "assets/people/mukund-gokhale.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/mukund-gokhale"
      },
      "photoWidth": 473,
      "photoHeight": 467
    },
    {
      "id": "vijay-kumar-kalyani",
      "hrEmployeeId": "",
      "publicSourceSlug": "vijay-kumar-kalyani",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Vijay Kumar Kalyani",
      "designation": "Professor of Practice",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:45.981255+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Neural networks, physics-informed neural networks, mathematical modelling, and mathematical seismology.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Vijaykumar-Kalyani.webp",
      "photoPath": "assets/people/vijay-kumar-kalyani.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/vijay-kumar-kalyani"
      },
      "photoWidth": 473,
      "photoHeight": 468
    }
  ],
  "biosciences": [
    {
      "id": "nithya-n-kutty",
      "hrEmployeeId": "",
      "publicSourceSlug": "nithya-n-kutty",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Nithya N Kutty",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Plant specialised metabolism, plant–microbe interactions, plant volatiles, metabolomics, and green chemistry.",
      "email": "nithya.kutty@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Nithya%20N%20Kutty.webp",
      "photoPath": "assets/people/nithya-n-kutty.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/nithya-n-kutty",
        "orcid": "https://orcid.org/0000-0002-2529-8080",
        "scholar": "https://scholar.google.co.in/citations?user=KFtqHjwAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57201300890#tab=metrics"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "shilpa-samir-chapadgaonkar",
      "hrEmployeeId": "",
      "publicSourceSlug": "shilpa-samir-chapadgaonkar",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Shilpa Samir Chapadgaonkar",
      "designation": "Associate Professor and Program Director",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Bioprocess and enzyme technology, biopharmaceutical production and purification, tissue engineering, disease models, and sustainable biotechnology.",
      "email": "shilpa.chapadgaonkar@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Shilpa-Samir-Chapadgaonkar.webp",
      "photoPath": "assets/people/shilpa-samir-chapadgaonkar.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/shilpa-samir-chapadgaonkar",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=14045418300"
      },
      "photoWidth": 474,
      "photoHeight": 486
    },
    {
      "id": "manasi-mishra",
      "hrEmployeeId": "",
      "publicSourceSlug": "manasi-mishra",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Manasi Mishra",
      "designation": "Associate Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Plant defence proteins and peptides, bioactive molecules, protein engineering, botanical therapeutics, molecular diversity, and evolution.",
      "email": "manasi.mishra@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Manasi%20Mishra.webp",
      "photoPath": "assets/people/manasi-mishra.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/manasi-mishra",
        "orcid": "https://orcid.org/0000-0002-3304-9105"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "rehan-deshmukh",
      "hrEmployeeId": "",
      "publicSourceSlug": "rehan-deshmukh",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Rehan Deshmukh",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Electrochemical and optical biosensors for pathogen detection, surface functionalisation, nanomaterials, PCR-based sensing, and enzyme technology.",
      "email": "rehan.deshmukh@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Rehan%20Deshmukh.webp",
      "photoPath": "assets/people/rehan-deshmukh.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/rehan-deshmukh",
        "orcid": "https://orcid.org/0000-0002-0261-102X",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57190178102"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "shikha-vikrant-gaikwad",
      "hrEmployeeId": "",
      "publicSourceSlug": "shikha-vikrant-gaikwad",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Shikha Vikrant Gaikwad",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Microbial metabolites and biosurfactants, bioprocess engineering, plant–microbe interactions, biostimulants, circular economy, and environmental biotechnology.",
      "email": "shikha.gaikwad@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Dr-Shikha-Gaikwad.webp",
      "photoPath": "assets/people/shikha-vikrant-gaikwad.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/shikha-vikrant-gaikwad",
        "scholar": "https://scholar.google.com/citations?hl=en&authuser=2&user=pD4ECgoAAAAJ"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "anup-atul-kale",
      "hrEmployeeId": "",
      "publicSourceSlug": "anup-atul-kale",
      "recordSource": "mitwpu-public-site",
      "name": "Prof. Dr. Anup Atul Kale",
      "designation": "Professor & Dean",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Nanobiotechnology, biomaterials and biomimetics, biosensors, point-of-care diagnostics, and nutraceuticals.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643cf4957126e1681716373.jpg",
      "photoPath": "assets/people/anup-atul-kale.jpg",
      "links": {},
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "mukul-sacchit-godbole",
      "hrEmployeeId": "",
      "publicSourceSlug": "mukul-sacchit-godbole",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Mukul Sacchit Godbole",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Cancer cell biology, breast and ovarian cancer, steroid-hormone signalling, metastasis, and microbiomes.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e392633aac1681799462.jpg",
      "photoPath": "assets/people/mukul-sacchit-godbole.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/mukul-sacchit-godbole"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "amruta-sameer-naik",
      "hrEmployeeId": "",
      "publicSourceSlug": "amruta-sameer-naik",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Amruta Sameer Naik",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Stem cell and bone biology, regenerative medicine, tissue engineering, biomaterial scaffolds, and osteomicrobiology.",
      "email": "amruta.naik@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/643e39346d2de1681799476.jpg",
      "photoPath": "assets/people/amruta-sameer-naik.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/amruta-sameer-naik",
        "orcid": "https://orcid.org/0000-0002-8023-6376",
        "scholar": "https://scholar.google.com/citations?user=dbz44YoAAAAJ&hl=en&authuser=1&oi=ao",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=35558053900"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "tejaswini-pachpor",
      "hrEmployeeId": "",
      "publicSourceSlug": "tejaswini-pachpor",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Tejaswini Pachpor",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Bioprocess technology, experimental design and optimisation, yeast biotechnology, bioethanol, and value-added biomolecules.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Tejaswini-Pachpor.webp",
      "photoPath": "assets/people/tejaswini-pachpor.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/tejaswini-pachpor"
      },
      "photoWidth": 270,
      "photoHeight": 267
    },
    {
      "id": "kausik-bhattacharyya",
      "hrEmployeeId": "",
      "publicSourceSlug": "kausik-bhattacharyya",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Kausik Bhattacharyya",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Infectious-disease biology, microbial and viral genomics, bioinformatics, host–pathogen interactions, and antimicrobial resistance.",
      "email": "kausik.bhattacharyya@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Kausik.webp",
      "photoPath": "assets/people/kausik-bhattacharyya.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/kausik-bhattacharyya",
        "orcid": "https://orcid.org/0000-0002-4033-676X",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=55313145700"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "bishnudeo-roy",
      "hrEmployeeId": "",
      "publicSourceSlug": "bishnudeo-roy",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Bishnudeo Roy",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Immunology, immune modulation, infection and immunity, inflammatory responses, antibody profiling, and single-cell sequencing.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Dr._Bishnudeo-Roy.webp",
      "photoPath": "assets/people/bishnudeo-roy.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/bishnudeo-roy"
      },
      "photoWidth": 364,
      "photoHeight": 368
    },
    {
      "id": "sachin-harle",
      "hrEmployeeId": "",
      "publicSourceSlug": "sachin-harle",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Sachin Harle",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Next-generation sequencing, metagenomics and microbiome analysis, whole-genome and transcriptome analysis, molecular docking, and molecular dynamics.",
      "email": "sachin.harle@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Dr.Sachin-Harle.webp",
      "photoPath": "assets/people/sachin-harle.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/sachin-harle",
        "scholar": "https://scholar.google.com/citations?user=1CuLqrEAAAAJ&hl=en"
      },
      "photoWidth": 364,
      "photoHeight": 364
    },
    {
      "id": "mandar-bopardikar",
      "hrEmployeeId": "",
      "publicSourceSlug": "mandar-bopardikar",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Mandar Bopardikar",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Molecular biophysics and biochemistry, protein aggregation, NMR spectroscopy, fluorescence methods, and neurodegenerative-disease models.",
      "email": "mandar.bopardikar@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Mandar-Bopardikar.webp",
      "photoPath": "assets/people/mandar-bopardikar.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/mandar-bopardikar"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "neha-bokey",
      "hrEmployeeId": "",
      "publicSourceSlug": "neha-bokey",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Neha Bokey",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Human gut microbiome, metagenomics and metabolomics, molecular biology, biochemistry, and phylogenetic analysis.",
      "email": "neha.bokey@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Dr-neha-bokey.webp",
      "photoPath": "assets/people/neha-bokey.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/neha-bokey"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "amit-kumar",
      "hrEmployeeId": "",
      "publicSourceSlug": "amit-kumar",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Amit Kumar",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Genetic and epigenetic regulation of plant haploid embryogenesis, cell totipotency and regeneration, speed breeding, photoperiod, and thermomemory.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Amit-Kumar.webp",
      "photoPath": "assets/people/amit-kumar.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/amit-kumar"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "shalaka-patil",
      "hrEmployeeId": "",
      "publicSourceSlug": "shalaka-patil",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Shalaka Patil",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Genome stability in cancer, DNA damage and repair, cancer epigenetics, phase separation, and optogenetic tools.",
      "email": "shalaka.patil@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Dr-Shalaka-Patil.webp",
      "photoPath": "assets/people/shalaka-patil.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/shalaka-patil",
        "orcid": "https://orcid.org/0000-0002-5859-4417",
        "scholar": "https://scholar.google.com/citations?user=3i4jVsgAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57225810076"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "meenakshi-shankar-iyer",
      "hrEmployeeId": "",
      "publicSourceSlug": "meenakshi-shankar-iyer",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Meenakshi Shankar Iyer",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Genomics, transcriptomics and metagenomics; protein sequence, structural and evolutionary analysis; protein design; and computational vaccinology.",
      "email": "meenakshi.iyer@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/DR-MEENAKSHI-IYER.webp",
      "photoPath": "assets/people/meenakshi-shankar-iyer.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/meenakshi-shankar-iyer",
        "orcid": "https://orcid.org/0000-0002-0488-7193",
        "scholar": "https://scholar.google.com/citations?user=IVkcvqQAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=58245455600"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "kirtikumar-kondhare",
      "hrEmployeeId": "",
      "publicSourceSlug": "kirtikumar-kondhare",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Kirtikumar Kondhare",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Molecular regulation of storage-root development and sprouting, transcriptomics and metabolomics, genome editing, plant transformation, and crop improvement.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Kirtikumar-Kondhare.webp",
      "photoPath": "assets/people/kirtikumar-kondhare.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/kirtikumar-kondhare"
      },
      "photoWidth": 473,
      "photoHeight": 467
    },
    {
      "id": "preethi-sunkara",
      "hrEmployeeId": "",
      "publicSourceSlug": "preethi-sunkara",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Preethi Sunkara",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:11:51.668782+00:00",
      "researchEvidence": "profile",
      "summary": "",
      "research": "Plant developmental biology, plant–pathogen interactions, combined biotic and abiotic stress, plant genetics, and molecular biology.",
      "email": "preethi.sunkara@mitwpu.edu.in",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/preethi-sunkara.webp",
      "photoPath": "assets/people/preethi-sunkara.webp",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/preethi-sunkara",
        "orcid": "https://orcid.org/0000-0002-3600-2089",
        "scholar": "https://scholar.google.com/citations?user=_bZD3msAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=57203310105"
      },
      "photoWidth": 473,
      "photoHeight": 468
    }
  ],
  "environmental-studies": [
    {
      "id": "pankaj-pramod-koparde",
      "hrEmployeeId": "",
      "publicSourceSlug": "pankaj-pramod-koparde",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Pankaj Pramod Koparde",
      "designation": "Program Coordinator & Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:03.099184+00:00",
      "researchEvidence": "profile",
      "summary": "Evolutionary ecologist working in urban ecology, biogeography, conservation science, biodiversity informatics, citizen science, and science communication.",
      "research": "Urban and evolutionary ecology; biogeography; biodiversity informatics; citizen science; science communication; odonates and owls.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/6442502d1f7061682067501.jpg",
      "photoPath": "assets/people/pankaj-pramod-koparde.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/pankaj-pramod-koparde",
        "orcid": "https://orcid.org/0000-0002-7418-8814",
        "scholar": "https://scholar.google.com/citations?user=xmcTPqsAAAAJ&hl=en",
        "scopus": "https://www.scopus.com/authid/detail.uri?authorId=55612726200"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "prasad-anil-kulkarni",
      "hrEmployeeId": "",
      "publicSourceSlug": "prasad-anil-kulkarni",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Prasad Anil Kulkarni",
      "designation": "Program Director and Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:03.099184+00:00",
      "researchEvidence": "profile",
      "summary": "Environmental scientist working across climate action, sustainability assessment, natural-resource management, and mangrove conservation.",
      "research": "SDGs; environmental impact assessment; life-cycle assessment; ESG; environmental project management and innovation; mangrove ecology.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/64425090c84a11682067600.jpg",
      "photoPath": "assets/people/prasad-anil-kulkarni.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/prasad-anil-kulkarni"
      },
      "photoWidth": 473,
      "photoHeight": 468
    },
    {
      "id": "soma-mishra",
      "hrEmployeeId": "",
      "publicSourceSlug": "soma-mishra",
      "recordSource": "mitwpu-public-site",
      "name": "Dr. Soma Mishra",
      "designation": "Assistant Professor",
      "employmentStatus": "unverified",
      "publicVisibility": "listed",
      "sourceObservedAt": "2026-07-23T08:12:03.099184+00:00",
      "researchEvidence": "profile",
      "summary": "Environmental engineer working on water systems, emerging contaminants, river- and lake-bank filtration, and sustainable wastewater treatment.",
      "research": "River- and lake-bank filtration; emerging contaminants; industrial and municipal wastewater treatment; bioaugmentation; phytoremediation; sustainable water and waste management.",
      "email": "",
      "photoSource": "https://mitwpu.edu.in/uploads/faculty_images/Soma-Mishra.webp",
      "photoPath": "assets/people/soma-mishra.jpg",
      "links": {
        "profile": "https://mitwpu.edu.in/faculty/soma-mishra"
      },
      "photoWidth": 473,
      "photoHeight": 468
    }
  ]
};
